### ISSUE TITLE
Very useful concept of Identity Server v3 especially using AngularJS parts

### ISSUE THREAD

**Issue by Jenanek** [GeertHuls/SecuredApi#1]
Hi,

I'm looking for implementation Indentity Server v3 with API (Resource server) and client with angularjs.

Your solution seems like very nice concept!
I look forward to trying it. I will be happy if you continue to develop and share code.

Thanks for your repository.
J.

**Comment by GeertHuls** [comment]
Thanks!

Yeah, I believe if you're going for that stack, then this project should give you a head start.

Enjoy!

Regards.
