### ISSUE TITLE
IIS Setup

### ISSUE THREAD

**Issue by James-1064** [GeertHuls/SecuredApi#3]
This project sounds like just what i'm trying to do, thanks...
I'm trying to setup IIS to get the projects to load from the solution, but VS stating "Could not find the server 'https://secured.local:449/......'
I have added secured.local to my host file.
Created a web site secure.local in IIS using the development ssl cert on port 449.
Create the web applications under secure.local.
Set app pool to .net 4
But, VS still complains about can't find server.
Any help appreciated, thanks.

**Comment by GeertHuls** [comment]
Looks like, you're on the right path.

Did you create 3 applications underneath your SecuredApi website?
You'll need to create
- identityserver (map to path: ..\SecuredApi\SecuredApi\IdentityServer)
- ResourceServer (map to path ..\SecuredApi\SecuredApi\ResourceServer)
- SpaClient (map to path: ..\SecuredApi\SecuredApi\SpaClient)

That should be all I guess. Also make sure you respect the case sensitivity when creating the 3 iis applications.

Regards.
